name: Frontend Deploy

on:
  push:
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Frontend Dependencies
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: ${{ runner.os }}-frontend-
      - name: Install Frontend Dependencies
        run: npm ci
      - name: Build Frontend
        run: npm run build
      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: frontend/dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Cache CDK Dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-cdk-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-cdk-
      - name: Install CDK dependencies
        run: npm ci
      - name: Download Frontend Artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend
          path: frontend/dist
      - name: Run AWS CDK Deploy
        run: npx cdk deploy --require-approval never
